### ISSUE TITLE
Reduce in Rosetta Code

### ISSUE THREAD

**Issue by Observatorio-de-Matematica** [reduce-algebra/reduce-algebra#67]
For some time if one was looking for Reduce in Rosetta Code there was redirected to Catamorphosis, but now is redirected to the category of the language https://rosettacode.org/wiki/Category:Reduce

Now everyone who has knowledge about Reduce can submit code for the tasks and help others to be aware of what can be done with Reduce.

I am not related to Rosetta Code staff, i am not doing this for SPAM, i am just interested Reduce be known.

**Comment by johnsonjh** [comment]
Good to have done, thanks.
