### ISSUE TITLE
Long sequence chokes redcsl

### ISSUE THREAD

**Issue by sola-aina** [reduce-algebra/reduce-algebra#74]
Hi reduce-devs,

The long sequence given in the link below fails in redcsl 
https://gist.github.com/sola-aina/e385aa5eb2eb0d7ffbccf8d9d0d9781a

redpsl appears to fare better (way faster) but when writing to a file exclamation marks appear before uppercase symbols. For example

g1 := !D2!E11!Dx1!Dx1;

instead of

g1 := D2E11Dx1Dx1;

Why?

Regards.

PS: Thanks for moving away from SourceForge. Its a dying platform. Logins no longer appear to work.

**Comment by chakravala** [comment]
Source forge is still the official forum for reduce algebra, this is only a
mirror.

**Comment by johnsonjh** [comment]
Thanks for your report!  Unfortunately, we don't use GitHub Issues to manage bug reports or assistance requests for this repository.  Instead, please see the [REDUCE Homepage](https://reduce-algebra.sourceforge.io) or the [REDUCE Support Page](https://sourceforge.net/projects/reduce-algebra/support) at Sourceforge for details on how to report a bug or get assistance with REDUCE.

(This report has been forwarded to https://sourceforge.net/p/reduce-algebra/bugs/171/)
